{% set name = "wrds" %}
{% set version = "3.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/wrds-{{ version }}.tar.gz
  sha256: 867af94c4a4fa8246ee02e82597d60d96d5b8300c380160154649b75fc018911

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=67
    - setuptools-scm >=7
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - packaging <=24.2
    - pandas >=2.2,<2.3
    - psycopg2-binary >=2.9,<2.10
    - sqlalchemy >=2,<2.1

test:
  imports:
    - wrds
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: Access WRDS data through PostgreSQL in Python.
  home: https://github.com/wharton/wrds/
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - FlipperPA
